platform :ios, '9.0'
target 'AgentX' do
pod 'Firebase'
pod 'Firebase/Messaging'
pod 'Firebase/Core'
  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

end


